// Install MiH Item Pack depending on engine version


ACTION_IF ENGINE_IS "bg1 totsc"
BEGIN
  PRINT "BG1 engine found, installing BG1 compatible item pack."

  INCLUDE "%MOD_FOLDER%/components/mih_item_pack_bg1.tpa"
END


ACTION_IF ENGINE_IS "bg2 tob bgee bg2ee"
BEGIN
  PRINT "BG2 engine or better found, installing full BGT item pack."

  INCLUDE "%MOD_FOLDER%/components/mih_item_pack_bgt.tpa"
END


// TODO: Icewind Dale


