// Made in Heaven item pack for the Baldur's Gate trilogy


// Generate generic extra damage .eff files

OUTER_FOR (i = 1; i <= 4; ++i)
BEGIN
  // Extra damage of various types.

  CREATE EFF "mh#crsh%i%"
    WRITE_LONG	0x0010 12	// HP: Damage
    WRITE_LONG	0x001c i
    WRITE_LONG	0x0020 0
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance

  CREATE EFF "mh#slsh%i%"
    WRITE_LONG	0x0010 12	// HP: Damage
    WRITE_LONG	0x001c i
    WRITE_LONG	0x0020 16777216
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance

  CREATE EFF "mh#prce%i%"
    WRITE_LONG	0x0010 12	// HP: Damage
    WRITE_LONG	0x001c i
    WRITE_LONG	0x0020 16777216
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance


  // Increase to-hit/damage against specific creatures.
  //
  // Some of these already exist in BG1/BG2, but have various errors,
  // so creating them all fresh here.

  CREATE EFF "undhit%i%"
    WRITE_LONG	0x0010 178	// THAC0 vs. Creature Type
    WRITE_LONG	0x001c IDS_OF_SYMBOL("general" "undead")
    WRITE_LONG	0x0020 3
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance
    WRITE_LONG	0x0060 i

  CREATE EFF "unddam%i%"
    WRITE_LONG	0x0010 179	// Damage vs. Creature Type
    WRITE_LONG	0x001c IDS_OF_SYMBOL("general" "undead")
    WRITE_LONG	0x0020 3
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance
    WRITE_LONG	0x0060 i

  CREATE EFF "lycnhit%i%"
    WRITE_LONG	0x0010 178	// Damage vs. Creature Type
    WRITE_LONG	0x001c IDS_OF_SYMBOL("race" "lycanthrope")
    WRITE_LONG	0x0020 3
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance
    WRITE_LONG	0x0060 i

  CREATE EFF "lycndam%i%"
    WRITE_LONG	0x0010 179	// Damage vs. Creature Type
    WRITE_LONG	0x001c IDS_OF_SYMBOL("race" "lycanthrope")
    WRITE_LONG	0x0020 3
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance
    WRITE_LONG	0x0060 i
END


// Instant death effect, no save

CREATE EFF "mh#death"
  WRITE_LONG	0x0010 13	// Death: Instant Death
  WRITE_LONG	0x001c 1
  WRITE_LONG	0x0020 8
  WRITE_SHORT	0x0024 1	// Permanent
  WRITE_SHORT	0x002c 100	// 100% chance


// Disrupt undead message

CREATE EFF "mh#udmsg"
  WRITE_LONG	0x0010 139	// Text: Display String
  WRITE_LONG	0x001c RESOLVE_STR_REF("Undead destroyed")
  WRITE_SHORT	0x0024 1	// Permanent
  WRITE_SHORT	0x002c 100	// 100% chance


// Copy .bam files over

COPY_LARGE "%MOD_FOLDER%/item_pack/bgt/bams" "override"


// Update itemexcl.2da

COPY_EXISTING "itemexcl.2da" "override"
  APPEND_FILE TEXT "%MOD_FOLDER%/item_pack/bgt/item_exclude.txt"


// mh#amul1 - Amulet against Undead

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#amul1.itm" "override"
  SAY NAME2 "Amulet against Undead"
  SAY IDENTIFIED_DESC "Amulet against Undead

This item looks quite old and judging by the style has been forged somewhere in Mulhorand, but the history of its creation is unknown.  It is possible that it was not created on Faerun at all but instead was brought on this world when the ancient Imaskari artificers magically abducted thousands of humans from another world to serve as their slaves.  When their deities found a way to enter Toril, these slaves revolted and formed the nation of Mulhorand.

The amulet is shaped like an ankh, the symbol of life, and it bears silver runes and symbols related to dawn, the sun, light and life, all things that are anathema to undead.  Wearing this amulet helps the bearer strike true against zombies, ghouls and other soulless horrors from beyond the grave.

STATISTICS:

THAC0: +3 vs. Undead
Damage: +3 vs. Undead
Weight: 3"


// mh#amul2 - Gem of Insight

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#amul2.itm" "override"
  SAY NAME2 "Amulet of Insight"
  SAY IDENTIFIED_DESC "Gem of Insight

This necklace consists of a large multi-faceted diamond on a delicate silver chain.  If one peers inside the diamond, the holy symbol of Oghma, god of knowledge can be seen at the center.  Most likely this item was created by the clergy of Oghma, but for what exact purpose is unknown.  Most likely, it was just to advance knowledge and ideas in general.

While worn, this magical gem enhances both the intelligence and wisdom of the wearer.  If the wearer so chooses the gem can enhance their intelligence permanently, but by doing so the gem and the wisdom it brings will be permanently lost.

STATISTICS:

Intelligence: +1 bonus
Wisdom: +1 bonus
Special: Can enhance intelligence permanently, but by doing so the gem is forever lost.
Weight: 1"


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= RESOLVE_STR_REF("+1 Intelligence")
STR_VAR
  item			= "mh#amul2"
END


// mh#amul3 - Necklace of Prayer Beads

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#amul3.itm" "override"
  SAY NAME2 "Necklace of Prayer Beads"
  SAY IDENTIFIED_DESC "Necklace of Prayer Beads

Necklaces like these are sometimes created by the clergy of Tymora for sale to adventurers in need of a little extra preparation.  The clergy claims they are doing it to help adventurers be successful in their cause, but the more cynical remark that an adventurer already has to be pretty successful in order to even be able to afford one of these items.

STATISTICS:

Abilities: Bless 3/day, Cure Serious Wounds 1/day and Neutralize Poison 1/day, all as a 12th level cleric

Only usable by:
  Cleric
  Druid"

  // BG1 engine does not support charges per day
  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION ALTER_ITEM_HEADER
      INT_VAR
      charges		= 10
      flag_recharge	= 0
    END
  END


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= 12089		// "Bless"
  $tip(2)		= 12114		// "Cure Serious Wounds"
  $tip(3)		= 12115		// "Neutralize Poison"
STR_VAR
  item			= "mh#amul3"
END


// mh#amul4 - Periapt of Health

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#amul4.itm" "override"
  SAY NAME2 "Periapt of Health"
  SAY IDENTIFIED_DESC "Periapt of Health

This blessed jewel protects the wearer from all kinds of diseases mundane and magical, except for lycanthropy which is more a curse than a disease.  The wearer is also immune to attacks that would blind or deafen her.

STATISTICS:

Special: Wearer is immune to blindness, deafness and disease.
Weight: 1"

  // Apply CamDawg's macros for blindness, deafness and disease on BG2 or better engine
  PATCH_IF NOT ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_blindness_arrays
    END

    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_deafness_arrays
    END

    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_disease_arrays
    END
  END


// mh#armr1 - Green Dragon Scale

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#armr1.itm" "override"
  SAY NAME2 "Green Dragon Scale"
  SAY IDENTIFIED_DESC "Green Dragon Scale

This armor was expertly crafted by the dwarven smith Brokk from green dragon scales which <CHARNAME> found in the depths of Durlag's Tower.  Whom exactly slew the green dragon that these scales were harvested from is not known, but most likely it was the dwarven hero Durlag himself.

STATISTICS:

Armor Class: 0
Special: wearer is immune to poison
Weight: 8
Requires: 6 Strength

Not usable by:
 Bard
 Mage
 Thief"

  // Apply CamDawg's full poison immunity macro on BG2 or better engine
  PATCH_IF NOT ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_poison_arrays
    END
  END


// mh#armr2 - Eversing +2

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#armr2.itm" "override"
  SAY NAME2 "Eversing +2"
  SAY IDENTIFIED_DESC "Plate Armor +2: 'Eversing'

This magnificent set of silvered plate was created hundreds of years ago by a joined effort between master dwarven smiths from Dorn's Deep and elven high mages from the Hand of the Seldarine.  Unfortunately it was stolen from the dwarven vaults and later found on the body of an orc chieftain by the elves, sowing deep distrust between the two races.  This eventually led to the fall of both the Hand of the Seldarine and Dorn's Deep to orc hordes.

The silver coating on this armor never loses its shine and may occasionally deflect hostile spells away from the wearer.

STATISTICS:

Armor Class: 1
Saving Throws: +2 vs. Spells
Magic Resistance: +5%
Weight: 25
Requires: 12 Strength
Not Usable By:
 Bard
 Druid
 Mage
 Thief"


// mh#armr3 - Winter Wolf Hide +1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#armr3.itm" "override"
  SAY NAME2 "Winter Wolf Hide +1"
  SAY IDENTIFIED_DESC "Winter Wolf Hide +1

Expertly sown together for <CHARNAME> by the elven seamstress Tania, this hide armor is actually surprisingly comfortable.  The luxurious white winter wolf pelts keep the wearer pleasantly warm in the highlands of the Cloudpeaks, or any other cold place for that matter.  Tania seems to have woven a little elven magic into it as well, as some of the winter wolf's immunity to cold has been preserved and the armor restricts thieves only half as much as hide armor should.

However, since hide armor has a reputation as 'barbaric', and still remains somewhat uncomfortable and smelly, shops generally buy and sell it for a fairly low price.

STATISTICS:

Armor Class: 5
Cold Resistance: +30%
Penalties:
  Stealth: -10%
  Lockpicking: -5%
  Find/Remove Traps: -5%
  Pick Pockets: -15%
Weight: 30

Not usable by:
 Mage"


// mh#belt1 - Girdle of Dwarvenkind: 'Moradin's Blessing'

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#belt1.itm" "override"
  SAY NAME2 "Girdle of Dwarvenkind"
  SAY IDENTIFIED_DESC "Girdle of Dwarvenkind: 'Moradin's Blessing'

Priests of Moradin sometimes grant belts like this one to non-dwarves who have done a great service to dwarvenkind.  Most dwarves will treat anyone wearing one of these as a trusted friend and clansmember.

The sturdy belt contains a powerful blessing that grants the wearer many of the racial bonuses that dwarves enjoy, like infravision and enhanced constitution.  Unfortunately for the wearer, some of the dwarven gruffness also rubs off on them, hurting their charisma slightly.

STATISTICS:

Constitution: +1 bonus
Charisma: -1 penalty
Saving Throws: +3 vs. Poison, Wands and Spells
Special: wearer gains infravision like a dwarf
Weight: 2

Not usable by:
 Dwarf
 Gnome"


// mh#belt2 - Girdle of Cloud Giant Strength

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#belt2.itm" "override"
  SAY NAME2 "Girdle of Cloud Giant Strength"
  SAY IDENTIFIED_DESC "Girdle of Cloud Giant Strength

This enchanted girdle belonged to the dwarven hero Durlag, and is the likely cause for many of the heroic feats attributed to him, although how it came into his possession is not known.  The design and apparent age suggests a Netherese origin, but other than that it defies identification.

After the fateful tenday when Durlag was forced to slay the dopplegangers that had replaced his family and taken over his home, this magical belt was forgotten on one of the many heaps of treasure deep within the deadly tower, until it was recovered by <CHARNAME>.

STATISTICS:

Strength: set to 23
Weight: 2"


// mh#belt3 - Sunite Sash

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#belt3.itm" "override"
  SAY NAME2 "Sunite Sash"
  SAY IDENTIFIED_DESC "Sunite Sash

This scarlet sash is woven of fine red threat and gold wire.  Sashes like these are created by the clergy of Sune and worn by their most prominent members.  This particular one was worn by a Sunite whom was whispered to have a lover from another plane of existence.  However, the relation seems to not have been a beneficial one.  One day his corpse was drained of all life, lying naked on his bed.  Whomever was responsible had taken the sash with her.

STATISTICS:

Armor Class: +2 bonus
Charisma: +2 bonus
Ability: Casts Burning Hands 1/day
Weight: 2"

  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    // BG1 engine does not support charges per day
    LAUNCH_PATCH_FUNCTION ALTER_ITEM_HEADER
      INT_VAR
      charges		= 12
      flag_recharge	= 0
    END
  END


// mh#blun1 - Slime Crusher +1

CREATE EFF "mh#blun1"
  WRITE_LONG	0x0010 178	// THAC0 vs. Creature Type
  WRITE_LONG	0x001c IDS_OF_SYMBOL("race" "slime")
  WRITE_LONG	0x0020 4
  WRITE_SHORT	0x0024 1	// Permanent
  WRITE_SHORT	0x002c 100	// 100% chance
  WRITE_LONG	0x0060 3

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#blun1.itm" "override"
  SAY NAME2 "Slime Crusher +1"
  SAY IDENTIFIED_DESC "Morning Star +1, +4 vs. Slimes: 'Slime Crusher'

This enchanted morning star was crafted by a troll shaman of the Silver Marshes in an effort to deal with an infestation of mustard jellies.  It was effective eventually, but the tribe suffered heavy losses in the process and was later easily wiped out by a band of human- and dwarven adventurers.

This morning star is considered a +4 weapon for purposes of what it can hit, but against enemies that aren't slimes it performs as a +1 weapon only.

STATISTICS:

THAC0: +1, +4 vs. Slimes
Damage: 2d4 +1, +4 vs. Slimes
Damage type: crushing
Weight: 10
Speed Factor: 6
Proficiency Type: Flail/Morning Star
Type: 1-handed
Requires: 11 Strength
Not Usable By:
 Druid
 Mage
 Thief"


// mh#blun2 - Blessed Mace of Ordona +2

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#blun2.itm" "override"
  SAY NAME2 "Blessed Mace of Ordona +2"
  SAY IDENTIFIED_DESC "Mace +2: 'Blessed Mace of Ordona'

Ordona was a faithful elven cleric of Corellon Larethian hundreds of years ago, and at one point her mace was blessed with special powers against undead and fiends, the creatures she abhored the most.  When Ordona felt the Call and traveled to Evermeet, she gifted her mace to a fellow adventurer, feeling that it would see better use on the mainland than in the elven paradise.  What happened afterwards is unclear, but the mace has since then had a peculiar record of always showing up exactly where it is needed the most - that is, where there are undead and fiends to fight.

STATISTICS:

STATISTICS:

Special: Wielder is permanently affected by a double-strength Bless spell.
THAC0: +2 bonus
Damage: 1D6 +3, +5 against undead and fiends
Damage type: crushing
Weight: 7
Speed Factor: 5
Proficiency Type: Mace
Type: 1-handed
Requires: 10 Strength

Not usable by:
 Druid
 Mage
 Thief
 Evil characters"

  // Prevent stacking with Bless spell if possible
  PATCH_IF NOT ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION CLONE_EFFECT
      INT_VAR
      match_opcode	= 130	// State: Bless
      opcode		= 206	// Protection: from Spell
      parameter1	= 0
      parameter2	= 0
      STR_VAR
      resource		= "sppr101"
    END
  END


// mh#boot1 - Feather Tabi

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#boot1.itm" "override"
  SAY NAME2 "Feather Tabi"
  SAY IDENTIFIED_DESC "Feather Tabi: 'Boots of the Master Ninja'

These enchanted split-toe boots hail from faraway Kara-Tur and are a rare sight on the Sword Coast.  The exact process of enchanting them is only known to some clans of ninja and they are quite secretive about it.  How this pair made it all the way to the Sword Coast is unclear.  Most likely, their former owner met with disaster while on a mission and was forced to leave them behind.  Whether he or she is still alive and still looking for them remains to be seen.

While worn these boots greatly reduces the force the wearer's weight excerts on the surface they are walking over.  This makes it a lot easier to walk silently, and also reduces the likelihood of setting off certain traps.

STATISTICS:

Stealth: +25%
Find/Remove Traps: +10%
Weight: 2

Only usable by:
 Thief"


// mh#boot2 - Boots of Striding and Springing

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#boot2.itm" "override"
  SAY NAME2 "Boots of Striding and Springing"
  SAY IDENTIFIED_DESC "Boots of Striding and Springing

These enchanted boots make the wearer exceptionally light on her feet, allowing her to sprint, dash and tumble with ease.  This makes the wearer harder to hit in battle, and allows for quicker movement.  No details about previous owners of this specific pair are known, it's possible they are relatively new and haven't been worn by anyone famous or notorious enough to be noteworthy yet.

STATISTICS:

Armor Class: +1 bonus
Movement: +2 bonus
Weight: 4"


// mh#boot3 - Boots of Gravewalking

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#boot3.itm" "override"
  SAY NAME2 "Boots of Gravewalking"
  SAY IDENTIFIED_DESC "Boots of Gravewalking

There are many stories about vile necromancers and wicked witches, and there will be no doubt many more.  Despite the dangers, many are lured in by the promises of dark powers and lies of infernal voices, seeking that which mortals were never meant to have.  One such individual was Abdal el Hagreb, a mysterious wizard from the Shining South.  Always seeking more power no matter what the prize, Abdal consulted with efreet and fiends who guided him in the construction of magical items of power.  As his infamy spread, many sought to eliminate the evil wizard, but none ever succeeded.

However, one day the wizard's tower and surrounding countryside were enveloped in a mysterious mist and just vanished, like they had never been there.  Nobody ever saw or heard from Abdal ever again.  Although legend has it that he has been transported to a dark place of nightmares, nobody really knows for sure just what happened exactly, and few people actually care.

These boots were one of the many vile items Abdal created.  Crafted from the cured skins of human bodies the mad wizard exhumed from their graves and enchanted by unspeakable rites, they brim with necromantic power.  How they came to leave his possession is not exactly known, although one story claims that they were stolen by an apprentice just before the mists claimed the tower.

STATISTICS:

Abilities: Casts Vampiric Touch 1/day and Animate Dead 1/day as a 10th level wizard
Weight: 4

Not usable by:
 Good characters"

  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    // BG1 engine does not support charges per day
    LAUNCH_PATCH_FUNCTION ALTER_ITEM_HEADER
      INT_VAR
      charges		= 12
      flag_recharge	= 0
    END
  END


// mh#brac1 - Bracers of Winter's Chill

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#brac1.itm" "override"
  SAY NAME2 "Bracers of Winter's Chill"
  SAY IDENTIFIED_DESC "Bracers of Winter's Chill

Not all items of great power have a heroic background, in fact just as many if not more are made by unscrupulous wizards out of vanity or greed, or by evil clerics at the command of their dark deities.  This particular item is an example of the latter, created by a cleric of Auril.  The Frost Maiden commands her followers to snuff all fires and open all structures to the icy cold, making the northern lands and eventually the entire world into a frozen hell with no light or warmth.  Of course many more benevolent powers seek to oppose such dark designs, and this struggle continues in the cold northern lands of Faerun to this day.

These bracers were forged as a weapon to be used by the followers of Auril, but one of their number had a crisis of faith and defected from the church, taking the bracers with her.  She fled south to escape Auril's icy grasp, and made it all the way to the Sword Coast before assassins sent by her former church caught up with her.  Fortunately for her, a passing group of adventurers foiled the assassination attempt, and out of thankfulness she joined them.  They had many more adventures together, until one day they ventured into the depths of Durlag's Tower and were never seen again.

STATISTICS:

Armor Class: base 4
Fire Resistance: +30%
Cold Resistance: +30%
Abilities: Casts Ice Storm and Cone of Cold 1/day each.
Weight: 2

Only usable by:
 Mage (single- or multi-class)"

  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    // BG1 engine does not support charges per day
    LAUNCH_PATCH_FUNCTION ALTER_ITEM_HEADER
      INT_VAR
      charges		= 12
      flag_recharge	= 0
    END
  END


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= 12062		// "Ice Storm"
  $tip(2)		= 12066		// "Cone of Cold"
STR_VAR
  item			= "mh#brac1"
END


// mh#brac2 - Gauntlets of the Dwarven King

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#brac2.itm" "override"
  SAY NAME2 "Gauntlets of the Dwarven King"
  SAY IDENTIFIED_DESC "Gauntlets of the Dwarven King

These gauntlets belonged to Garumn Battlehammer, grandfather to Bruenor Battlehammer, who was killed in the battle against the dragon Shimmergloom and his hordes of duergar.  However, when Bruenor returned to Mithral Hall centuries later and found the dusty bodies of his father and grandfather, the gauntlets were nowhere to be found, presumably taken by the duergar.

STATISTICS:

Armor Class: +1 bonus
Hit Points: +5 maximum
Weight: 5

Only usable by:
 Fighter
 Paladin
 Ranger"


// mh#btax1 - Foesplitter +1

CREATE EFF "mh#btax1"
  WRITE_LONG	0x0010 12	// HP: Damage
  WRITE_LONG	0x001c 1
  WRITE_LONG	0x0020 16777216	// Slashing
  WRITE_SHORT	0x0024 1	// Permanent
  WRITE_SHORT	0x002c 100	// 100% chance
  WRITE_LONG	0x0038 1	// # dice
  WRITE_LONG	0x003c 8	// # sides

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#btax1.itm" "override"
  SAY NAME2 "Foesplitter +1"
  SAY IDENTIFIED_DESC "Battle Axe of Sharpness +1: 'Foesplitter'

Forged centuries ago by the shield dwarves of the north, Foesplitter is a fearsome weapon.  It earned its name and reputation when its first owner, the dwarven hero Gorhan Axebeard, used it to literally cleave an orc chieftain in half.  This demoralized the horde so much that they ran and hid, and did not return for almost twenty years.  Unfortunately when they eventually did return they caught the dwarves by surprise and completely razed their stronghold.  The axe was taken as a war trophy until it was reclaimed by a human adventurer a few years later.  Since then the axe has been in the hands of several humans and dwarves, and even the odd elf or two, all over the Sword Coast from Waterdeep to Amn.

This axe has been crafted entirely from darksteel, both the blade and handle.  The cutting edge is magically honed to razor sharpness and will never chip or get dull.  This deadly business end easily chops through even magical defenses, one of the previous owners is known to have sliced the arm of an iron golem clean off.  The lower end is wrapped in sturdy leather for a better grip, but this is the only non-metallic part of the entire axe.

This weapon is considered a +3 weapon for purposes of what it can hit, even though it only functions as a +1 weapon.

STATISTICS:

Damage: 1d8 +1, 10% chance of double damage
Damage Type: Slashing
THAC0: +1
Weight: 7
Speed Factor: 6
Proficiency Type: Axe
Type: 1-handed

Not usable by:
 Druid
 Cleric
 Mage 
 Thief"

// mh#btax2 - Trollkiller +3

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#btax2.itm" "override"
  SAY NAME2 "Trollkiller +3"
  SAY IDENTIFIED_DESC "Battle Axe +3: 'Trollkiller'

This was the favored weapon of the dwarven hero Durlag 'Trollkiller', and true to its name he ended many a troll's life with it, not to mention several greater foes including a dragon.  This was also the weapon he used in that terrifying tenday when he fought to reclaim his tower from the dopplegangers that had infiltrated and murdered his clan.

After the battle, he could no longer bear to look at it, and for many years it laid on a forgotten pile of treasure at the bottom of the death trap that Durlag had reshaped his tower into.  It was eventually reclaimed by <CHARNAME> when <PRO_HESHE> finally made <PRO_HISHER> way through many deadly traps and challenges.

STATISTICS:

THAC0: +3 bonus
Damage: 1d8 +3, 70% change of +1d3 acid damage, 10% chance of +1d10 acid damage (these stack)
Damage Type: Slashing (and Acid)
Weight: 7
Speed Factor: 4
Proficiency Type: Axe
Type: 1-handed
Requires: 10 Strength

Not usable by:
 Cleric
 Druid
 Mage
 Thief"


// mh#btax3 - Redethemar +4

COPY "%MOD_FOLDER%/item_pack/bgt/spells/mh#btax3.spl" "override"

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#btax3.itm" "override"
  SAY NAME2 "Redethemar +4"
  SAY IDENTIFIED_DESC "Battle Axe +4: 'Redethemar'

This powerfully enchanted axe, which was wielded by several elven heroes in the past, is one of the treasures of the elven nation of Evermeet.  It having been moved to Suldanessenar is a good indication of how serious a problem the return of the Exile was to the elves.

While not intelligent, Redethemar does seem to have some empathic ability.  Evil people find the axe twisting in their grasp and refusing to strike anything at all.  In the hands of a worthy wielder it is a mighty weapon indeed, its powerful enchantment making it strike true and deal massive damage.  In addition to that, once per day Redethemar can be struck against the ground to create a local earthquake that will damage the wielder's enemies but won't affect the wielder and their allies.

STATISTICS:

Ability: Creates an earthquake once per day, dealing 5d10 damage to all enemies (save for half)
THAC0: +4 bonus
Damage: 1d8 +4
Damage Type: slashing
Weight: 4
Speed Factor: 3
Proficiency Type: Axe
Type: 1-handed
Requires: 10 Strength

Not usable by:
 Cleric
 Druid
 Mage
 Thief
 Evil characters"


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= "-1"
  $tip(2)		= 45054		// "Earthquake"
STR_VAR
  item			= "mh#btax1"
END


// mh#clck1 - Mutamin's Cloak

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#clck1.itm" "override"
  SAY NAME2 "Mutamin's Cloak"
  SAY IDENTIFIED_DESC "Mutamin's Cloak

This cloak was worn by the mad wizard Mutamin before <CHARNAME> slew him in the field east of Beregost.  There is no known prior history, most likely the mad gnome created it himself so he would be safe around his 'pets'.

STATISTICS:

Special: wearer is immune to all forms of petrification
Weight: 3"

  // Apply CamDawg's full petrification immunity macro on BG2 or better engine
  PATCH_IF NOT ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_petrification_arrays
    END
  END


// mh#clck2 - Battlecloak of Vycaena

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#clck2.itm" "override"
  SAY NAME2 "Battlecloak of Vycaena"
  SAY IDENTIFIED_DESC "Battlecloak of Vycaena

This voluminous, emerald-green cloak is trimmed with intricate designs done in gold thread.  Each of its two clasps is a golden disk engraved with the crest of a long-extinct Calishite noble family and set with a small emerald.  This alone would already make the cloak worth a small fortune, but it also bears a powerful enchantment to protect its wearer in battle.

The exact method of making these cloaks is known to only a few reclusive wizards in the Shining South, and the precious gems and rare materials involved in the process make creating a new one a hard and dangerous task.  As a result, only about a dozen of these cloaks are known to exist, and for one to make its way to the Sword Coast is a rare occurrence indeed.

STATISTICS:

Armor Class: +4 bonus
Saving Throws: +1 bonus
Weight: 3"


// mh#clck3 - Cloak of Arachnida

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#clck3.itm" "override"
  SAY NAME2 "Cloak of Arachnida"
  SAY IDENTIFIED_DESC "Cloak of Arachnida: 'Lloth's Caress'

This dark cloak was created by drow sorcerers, but how it came to leave their dark realm is not exactly known.  Most likely an overconfident drow was slain during a nightly surface raid and the cloak taken from his corpse.  Precious little is known about what happened to it on the surface either, something in the dark elven magic used to create this item seems to resist exact divination.  A few adventurers are known to have used it on various quests, but details are sketchy at best.

The wearer of this cloak can easily move through all spider webs without getting stuck, including those created by the wizard spell Web.  It also helps in resisting the poisons of arachnids.

STATISTICS:

Saving Throws: +2 vs. Poison
Special: Wearer is immune to the Web spell and all spider webbing.
Abilities: Casts Web as a 12th level wizard twice per day.
Weight: 3"

  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    // BG1 engine does not support charges per day
    LAUNCH_PATCH_FUNCTION ALTER_ITEM_HEADER
      INT_VAR
      charges		= 20
      flag_recharge	= 0
    END
  END
  ELSE
  BEGIN
    // Apply CamDawg's full web immunity macro on BG2 or better engine
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_web_arrays
    END
  END


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= 12057		// "Web"
STR_VAR
  item			= "mh#clck3"
END


// mh#clck4 - Cloak of Stars

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#clck4.itm" "override"
  SAY NAME2 "Cloak of Stars"
  SAY IDENTIFIED_DESC "Cloak of Protection +3: 'Cloak of Stars'

At first glance this appears to be a finely woven but otherwise unremarkable blue cloak, but powerful magic lies within.  Upon closer look, faint stars can be seen floating in the deep blue, as if the cloak were actually a piece of the night sky.

A creation of the mysterious elven high mages of Evermeet, this may be one of the most powerful defensive items in all of Faerun.  How it made it all the way to the mainland from the elven nation is not known, but one should assume that the elves are still looking for it and would do almost anything to see their treasure returned.

STATISTICS:

Armor Class: +3 bonus
Saving Throws: +3 bonus
Special: Wearer is permanently invisible
Weight: 3"


// mh#dagg1 - Mage Masher +1

CREATE EFF "mh#dagg1"
  WRITE_LONG	0x0010 178	// THAC0 vs. Creature Type
  WRITE_LONG	0x001c IDS_OF_SYMBOL("class" "mage")
  WRITE_LONG	0x0020 5
  WRITE_SHORT	0x0024 1	// Permanent
  WRITE_SHORT	0x002c 100	// 100% chance
  WRITE_LONG	0x0060 1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#dagg1.itm" "override"
  SAY NAME2 "Mage Masher +1"
  SAY IDENTIFIED_DESC "Dagger +1, +2 vs. Mages: 'Mage Masher'

After a foiled attempt to break into a local wizard's tower, the thief Vernon the Bold was so utterly humiliated that he developed a maniacal hatred of all mages.  He kidnapped another mage named Borin the Red and forced the hapless fellow to make this dagger, after which he slew the unfortunate man with his own creation.  Vernon then went on a killing spree, slaughtering any and all mages he came across.  Inevitably, he eventually bit off more than he could chew by attacking a trio of red wizards.  After their Fireballs and Lightning Bolts had stuck, this dagger was pretty much all that was left of the mad thief.

This dagger is always considered +2 for purposes of what it can hit, but it functions as only a +1 weapon against most enemies.  Against dual- and multi-classed mages (including ogre mages), it is still only +1 to hit, but it deals +2 damage.  Only against single-class mages does it function as a full +2 dagger.

STATISTICS:

THAC0: +1 bonus, +2 against single-class mages
Damage: 1d4 +1, +2 against all mages (including ogre mages)
Damage type: piercing
Weight: 1
Speed Factor: 1
Proficiency Type: Dagger
Type: 1-handed
Requires: 3 Strength

Not usable by:
 Cleric"


// mh#dagg2 - Catclaw +3

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#dagg2.itm" "override"
  SAY NAME2 "Catclaw +3"
  SAY IDENTIFIED_DESC "Dagger +3: 'Catclaw'

This well-made, finely balanced dagger was the property of a mysterious rogue known only as 'The Gray Mouser'.  A charismatic and notorious womanizer, the Mouser was far more interested in stealing hearts than treasure.  He has been seen in several cities on Faerun, sometimes in the company of a huge Northern barbarian named Fafhrd, who apparently shared his lecherous fondness of members of the opposite sex.  Nobody has ever been able to find out where they hale from; when asked they claimed a city named 'Lankhmar' was their home, but no city or town by that name exists anywhere on Faerun.

One affair with a twin pair of noblewomen in Waterdeep ended with the two having to beat a hasty retreat, and it was apparently on this occasion that the Mouser lost Catclaw.  He has yet to come back to reclaim it, and it is not known if he is even looking for it.

While the dagger functions well enough, a peculiarity in the enchantment suggests it might not have been created in Faerun, but somewhere else where magic functions slightly differently.  Whether Fafhrd and the Gray Mouser truly were travelers from another plane of existence nobody knows for sure, but such things are not unheard of in the Forgotten Realms.

STATISTICS:

Dexterity: +1 bonus
Stealth: +10% bonus
THAC0: +3 bonus
Damage: 1d4 +3
Damage Type: Piercing
Weight: 1
Speed Factor: 0
Proficiency Type: Dagger
Type: 1-handed
Requires: 3 Strength

Not usable by:
 Cleric"


// mh#hamm1 - Thronumin +3

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#hamm1.itm" "override"
  SAY NAME1 "Thronumin +3"
  SAY IDENTIFIED_DESC "War Hammer +3, Defender: 'Thronumin'

Thronumin, 'The Hammer of the Meteor', was forged almost a thousand years ago.  A meteor from Realmspace struck Aber-Toril, falling into a remote area of the Cloudpeak mountains and burying itself deep underground.  Dwarves from a now forgotten clan eventually tunneled to it and found that the meteor's core was almost pure iron.  From it a number of powerful weapons and armor were forged, but most have have been lost over the years.

Several dwarven runes have been inscribed into the head, glowing with power.  The enchantment on this weapon is quite formidable, not only enabling it to strike hard and true but also granting additional protection to the wielder.

STATISTICS:

Armor Class: +1 bonus
THAC0: +3 bonus
Damage: 1D4 +4
Damage type: crushing
Weight: 4
Speed Factor: 1
Proficiency Type: War Hammer
Type: 1-handed
Requires: 9 Strength

Not usable by:
 Druid
 Mage
 Thief"


// mh#helm1 - Helm of Valor

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#helm1.itm" "override"
  SAY NAME2 "Helm of Valor"
  SAY IDENTIFIED_DESC "Helm of Valor

These ornate golden helms are sometimes worn into battle by elven generals and commanders of Evermeet, Evereska or other elven nations.  This particular one was found in the ruins of Myth Drannor and probably belonged to an elven commander defending the city against the Army of Darkness.

Wearing this helm allows one to mentally will arrows and other projectiles away, making it less likely that one strikes true and reducing the damage even when this happens.  This allows the elven commander to remain upright even when under fire, and serve as an inspiration to his men.  However, because the helm operates on the willpower of the wearer, it can only be used effectively by people with high wisdom.

STATISTICS:

Armor Class: +3 vs. Missiles
Special: Protects against critical hits, reduces missile damage by 50%
Requires: 13 Wisdom
Weight: 2

Not usable by:
 Bard
 Mage
 Thief"


// mh#helm2 - Wizard's Hat

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#helm2.itm" "override"
  SAY NAME2 "Wizard's Hat"
  SAY IDENTIFIED_DESC "Wizard's Hat

Enchanted wizard hats of this type are fairly common in the Shining South, but up north they are rarely seen.  Although the wizards of the north appreciate its beneficial enchantments just as much as their southern bethren, they feel that the design is horridly out of fashion and wearing one all too often results in them being on the receiving ends of jokes - and the jokers being on the receiving end of a Polymorph Other spell.

STATISTICS:

Armor Class: +1 bonus
Spells: +1 third level spell

Only useable by:
 Mage (single- and multi-class)"


// mh#helm3 - Helm of the Dwarven Lords

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#helm3.itm" "override"
  SAY NAME2 "Helm of the Dwarven Lords"
  SAY IDENTIFIED_DESC "Helm of the Dwarven Lords

This enchanted helmet, forged from an unknown red alloy, once belonged to the royal family of the dwarven kingdom of Delzoun.  It would traditionally be worn by the reigning king when he lead his troups into battle.  It was lost in the Year of the Black Unicorn (-100) when the underground realm of Delzoun fell to creatures of the Underdark.  Despite several attempts by the dwarves, the helm was never recovered until a group of adventurers from the Dales found it in drow hands during a battle in the Twisted Tower more than nine hundred years later.  Since then, it has seen many different owners.

STATISTICS:

Special: Protects against critical hits,
wearer is immune to spells up to 3rd level
Regeneration: 2 hp/round
Weight: 2

Not usable by:
 Bard
 Mage
 Thief"

  // Use 1PP animation if available.
  PATCH_IF FILE_EXISTS_IN_GAME "wpnj0inv.bam"
  BEGIN
    WRITE_ASCII 0x0022 "J0" #2
  END

  // Apply CamDawg's spell immunity batches on appropriate engines
  PATCH_IF NOT ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_spell_level_1_arrays
    END

    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_spell_level_2_arrays
    END

    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_spell_level_3_arrays
    END
  END


// mh#helm4 - Shroudcrown

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#helm4.itm" "override"
  SAY NAME1 "Bronze Circlet"
  SAY NAME2 "Shroudcrown"
  SAY UNIDENTIFIED_DESC "Bronze Circlet

This is a simple circlet crafted from bronze and studded with fire agates.  It's too plain to be called a crown.  There is possibly some kind of enchantment on it, but nothing about its appearance hints on what it might be."
  SAY IDENTIFIED_DESC "Shroudcrown

This fire agate-studded bronze circlet holds considerable power over undead.  Hundreds of years ago, the insane Netherese necromancer Jobelo the Grand crafted it in order to protect him from his own unholy creations, after he was almost killed during one of his vile experiments with animating more powerful undead.  In the end it was still a horde of his own creations which he had lost control over that tore him to shreds.  His undead horde rampaged through a section of the High Forest for a couple of years until a combined effort of humans and elves wiped them out.

Although the crown itself is not cursed in any way, its owners do have an unfortunate tendency to meet similar messy ends as its creator at the claws of the very undead creatures against which it protects.  One should always keep in mind that no kind of protection is absolute, and undead horrors are nothing to be trifled with.

STATISTICS:

Ability: Casts Hold Undead 1/day as a 10th level wizard
Armor Class: +2 bonus vs. Undead
THAC0: +2 vs. Undead
Damage: +2 vs. Undead
Weight: 1"

  // Use 1PP animation if available.
  PATCH_IF FILE_EXISTS_IN_GAME "wpnjbinv.bam"
  BEGIN
    WRITE_ASCII 0x0022 "JB" #2
  END


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= 32379		// "Hold Undead"
STR_VAR
  item			= "mh#helm4"
END


// mh#ioun1 - Lush Emerald Ioun Stone

COPY_EXISTING "%MOD_FOLDER%/item_pack/bgt/items/mh#ioun1.itm" "override"
  SAY NAME1 "Ioun Stone"
  SAY NAME2 "Lush Emerald Ioun Stone"
  SAY UNIDENTIFIED_DESC "This is a small stone that floats in an orbit around the owner's head.  Simply equip the stone to set it in its orbit.  These obviously magical stones have different properties depending on their color."
  SAY IDENTIFIED_DESC "Lush Emerald Ioun Stone

Deep green ioun stones like this one are sometimes found between the roots of ancient oaks and other old trees.  Followers of Sylvanus consider them sacred to the Oak Father, and elves likewise consider them gifts from Rillifane Ralathil, the Leaflord.  Whether either of these gods actually has anything to do with the creation of these stones is unknown.  Some theorize they are buried treasures of old, probably from some tree-worshiping cult, while others speculate they are formed by some yet unknown natural or magical process.

In the hands of a druid or someone with a similarly strong connection to nature, this ioun stone becomes a powerful magical item.  But to anyone else it remains an inert, if very beautiful stone.

STATISTICS:

Armor Class: +1 bonus
Regeneration: 1 hp/5 rounds
Weight: 2

Only usable by:
 Druid"


// mh#ioun2 - Pearl of Power

COPY_EXISTING "%MOD_FOLDER%/item_pack/bgt/items/mh#ioun2.itm" "override"
  SAY NAME1 "Ioun Stone"
  SAY NAME2 "Pearl of Power"
  SAY UNIDENTIFIED_DESC "This is a small stone that floats in an orbit around the owner's head.  Simply equip the stone to set it in its orbit.  These obviously magical stones have different properties depending on their color."
  SAY IDENTIFIED_DESC "Pearl of Power

This pearl of exceptional quality has been enchanted to function as an ioun stone, allowing a mage to prepare and cast more spells than normal while the pearl is floating around his head.  Although the process itself has been well documented in various books of arcane lore, the difficulty of actually obtaining a pearl of suitable quality ensures that this remains a rather rare, and thus highly sought after item.

STATISTICS:

Spells: one extra 4th- and 5th level spell slot

Only usable by:
 Mage (single- and multi-class)"


// mh#lbow1 - Bow of Eletha

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#lbow1.itm" "override"
  SAY NAME2 "Bow of Eletha +2"
  SAY IDENTIFIED_DESC "Long Bow +2: 'Bow of Eletha'

This enchanted long bow belonged to a celebrated green elf warrior named Eletha.  After her death, it was kept in the treasury of Queen Amlaruil on Evermeet for many years until the queen gifted it to a human ally of the elves named Borvar Sha'Quessir.  Unfortunately Borvar and his party met their end when they tried to raid a red dragon's lair, and the bow laid in the dragon's hoard for a time until another adventuring party managed to slay the beast.  Although the elves would prefer to see it returned to Evermeet this is not a great priority and they will not press the issue as long as the item is not used against them.

STATISTICS:

Ability: Casts Magic Missile 3/day as a 12th level wizard
Special: Arrows shot from this bow have double normal range
THAC0: +3 bonus
Damage: +2 bonus
Weight: 2
Speed Factor: 5
Proficiency Type: Long Bow
Type: 2-handed
Requires: 6 Strength

Not usable by:
 Cleric
 Druid
 Mage
 Thief"


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= "-1"
  $tip(2)		= 12052		// "Magic Missile"
STR_VAR
  item			= "mh#helm4"
END


// mh#misc1 - Green Dragon Scales

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#misc1.itm" "override"
  SAY NAME2 "Green Dragon Scales"
  SAY IDENTIFIED_DESC "Green Dragon Scales

These shiny emerald scales were harvested from the corpse of a green dragon and seem to have been preserved in some way.  A capable smith should be able to craft these into a strong suit of armor."


// mh#misc2 - Meteoric Iron

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#misc2.itm" "override"
  SAY NAME2 "Meteoric Iron"
  SAY IDENTIFIED_DESC "Meteoric Iron

Although at first glance these seem to be nothing but rusty-red rocks, closer inspection reveals them to be fragments of an iron meteorite.  Such fragments hold traces of cosmic power, and a skilled smith might be able to fashion something good out of this."


// mh#misc3 - Telkiira

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#misc3.itm" "override"
  SAY NAME2 "Telkiira"
  SAY IDENTIFIED_DESC "Telkiira

This necklace is actually an elven artifact known as a telkiira, or lore-gem.  It records the memories and experiences of its owner, and allows her to draw upon the memories and experiences of previous owners.  Only elves or those with elven blood like a half-elf can use it, everyone else just gets a splitting headache from wearing it.

In addition, all but the most basic of its functions seem to be locked to only certain people.  There doesn't seem to be any way for you to pass the lock; it is keyed to a certain bloodline.  However, these gems are very precious to the elves and returning it to the rightful owner will likely result in a generous reward.

STATISTICS:

Intelligence: +2 bonus
Saving Throws: +2 vs. Spells

Only usable by:
 Elves
 Half-elves"


// mh#potn1 - Oil of Acid Resistance

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#potn1.itm" "override"
  SAY NAME2 "Oil of Acid Resistance"
  SAY IDENTIFIED_DESC "Oil of Acid Resistance

This is a black, viscous and non-flamable oil.  When applied to exposed equipment and skin, it confers virtual immunity to all acids and other corrosive agents.  All acid damage is reduced by 90%, on top of any other resistances the person might have.  The effect lasts for 10 turns, or until dispelled."


// mh#potn2 - Oil of Disenchantment

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#potn2.itm" "override"
  SAY NAME2 "Oil of Dispelling"
  SAY IDENTIFIED_DESC "Oil of Disenchantment

This sparkling golden fluid is an ethereal, rapidly evaporating thin oil.  When poured over a creature, it removes all dispelable magical effects from that creature unless it makes a saving throw versus wands at a -4 penalty."

  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION CLONE_EFFECT
      INT_VAR
      match_opcode	= 58	// Cure: Dispelable Effects
      opcode		= 141	// Graphics: Lighting Effects
      parameter1	= 1
      parameter2	= 12
      STR_VAR
      insert		= "last"
    END
  END
  ELSE
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_full_dispel_arrays
    END
  END


// mh#misc4 - Bag of Tricks

ACTION_IF NOT ENGINE_IS "bg1 totsc"
BEGIN
  ACTION_FOR_EACH animal IN "bearbl" "bearbr" "bearca" "beargr" "bearpo" "catjag" "catlio" "dogwa" "dogwi" "etterc" "gibber" "jaguar" "rabbit" "spidgi" "spidph" "wolf" "wolfdi" "wolfwi" "worg" "wyvern"
  BEGIN
    ACTION_IF NOT FILE_EXISTS_IN_GAME "%animal%su.cre"
    BEGIN
      ACTION_IF FILE_EXISTS_IN_GAME "%tutu_var%%animal%.cre"
      BEGIN
        COPY "%MOD_FOLDER%/item_pack/bgt/actors/%animal%.cre" "override/%animal%su.cre"
	  LAUNCH_PATCH_FUNCTION make_summon END
      END
      ELSE
      BEGIN
        COPY "%MOD_FOLDER%/item_pack/bgt/actors/%animal%su.cre" "override"
      END
    END

    ACTION_IF NOT FILE_EXISTS_IN_GAME "%animal%su.eff"
    BEGIN
      CREATE EFF "%animal%su"
        WRITE_LONG	0x0010 67	// Summon: Creature Summoning
        WRITE_SHORT	0x0024 1	// Permanent
        WRITE_SHORT	0x002c 100	// 100% chance
        WRITE_ASCII	0x0030 "%animal%su" #8
        WRITE_ASCII	0x0068 "spanisum" #8
    END
  END

  COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#misc4.itm" "override"
    SAY NAME1 "Bag"
    SAY NAME2 "Bag of Tricks"
    SAY UNIDENTIFIED_DESC "Bag

This seems to be a rather plain-looking burlap sack used to store common items, but something does not seem quite right.  Occasionally the bag seems to be moving, and when you reach inside, sometimes you feel something warm and fuzzy brush against your hand."
    SAY IDENTIFIED_DESC "Bag of Tricks: 'Thierdon's Crutch'

Thierdon was a druid in the forest of Tethyr hundreds of years ago.  Not very strong himself, he often relied on animal companions to aid him in battle against orc raiders and others who defiled the forest.  He found that this was a disadvantage when he was not in his beloved woods, and thus he created this magical bag so he would always have an animal companion with him no matter where he went.

The plain look of this enchanted burlap sack hides a powerful summoning magic inside.  Once per day, the owner may reach inside and pull a small fuzzy object out.  This object can be tossed up to 20 feet, and upon landing will turn into a random animal.  It can be anything from a tiny rabbit to a large wyvern, but the creature will always be friendly to the owner of the bag.  The creature will attack enemies to the best of its ability, until it is slain in battle or one turn has passed.  If no enemies are around, the animal might perform other services if it is able to do so.

STATISTICS:

Ability: Summons a single random animal once per day for one turn.
Weight: 2" 
END
ELSE
BEGIN
  COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#misc4-bg1.itm" "override/mh#misc4.itm"
    SAY NAME1 "Bag"
    SAY NAME2 "Bag of Tricks"
    SAY UNIDENTIFIED_DESC "Bag

This seems to be a rather plain-looking burlap sack used to store common items, but something does not seem quite right.  Occasionally the bag seems to be moving, and when you reach inside, sometimes you feel something warm and fuzzy brush against your hand."
    SAY IDENTIFIED_DESC "Bag of Tricks: 'Thierdon's Crutch'

Thierdon was a druid in the forest of Tethyr hundreds of years ago.  Not very strong himself, he often relied on animal companions to aid him in battle against orc raiders and others who defiled the forest.  He found that this was a disadvantage when he was not in his beloved woods, and thus he created this magical bag so he would always have an animal companion with him no matter where he went.

The plain look of this enchanted burlap sack hides a powerful summoning magic inside.  The bag contains several fuzzy objects which when taken out can be tossed up to twenty feet.  Upon landing, the object will become a cave bear that is friendly to the owner of the bag and will attack his enemies to the best of its ability.  Bears summoned will remain until slain, or one turn has passed, and the bag can be used twelve times before it is exhausted.

STATISTICS:

Ability: Summons a friendly cave bear up to twelve times.
Weight: 2" 
END


// mh#ring1 - Ring of Warmth

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring1.itm" "override"
  SAY NAME2 "Ring of Warmth"
  SAY IDENTIFIED_DESC "Ring of Warmth

A favorite among mountaineers, explorers and others whose activities get then into cold areas (including, of course, adventurers), the enchantment on this ring allows the wearer to remain comfortable in sub-zero temperatures.  Damage from extreme cold like white dragon breath or a wizard's Cone of Cold spell is also reduced.

STATISTICS:

Cold Resistance: +20%"


// mh#ring2 - Ring of the Neophyte

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring2.itm" "override"
  SAY NAME2 "Ring of the Neophyte"
  SAY IDENTIFIED_DESC "Ring of the Neophyte

A lesser version of the fabled Ring of Wizardry, rings like these are sometimes granted to a favorite apprentice when they complete their studies and are ready to set out on their own.  Other, more demanding masters might require their apprentices to complete forging one of their own as a sort of final exam.

This particular one bears a mage sigil that you don't recognize and does not respond to divination magic.  Its creator may be long forgotten - or value their privacy.

STATISTICS:

Spells: one extra 1st level spell slot

Only usable by:
 Mage (single- and multi-class)"


// mh#ring3 - Ring of Toughness

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring3.itm" "override"
  SAY NAME2 "Ring of Toughness"
  SAY IDENTIFIED_DESC "Ring of Toughness

This ring is a fairly plain steel band with only minimal enamel decoration.  It bears a minor enchantment that gives the wearer a small boost in vitality.

It's not known who created the first of these rings, but they occasionally show up in places where there has been a large conflict, probably created by combat priests or war wizards.

STATISTICS:

Hit Points: +3 maximum"


// mh#ring4 - Ring of Protection +3

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring4.itm" "override"
  SAY NAME2 "Ring of Protection +3"
  SAY IDENTIFIED_DESC "Ring of Protection +3: 'Ring of the Lich'

This ring is a creation of the Netherese lich Trachir the Elder, also known as the Ebon Skull.  When Karsus cast his fateful spell that destroyed High Netheril, Trachir had just completed the final rituals and drank the lethal potion that would transform his body into an undead horror.  Trachir's enclave plunged into the Sea of Swords several miles from the coast of Candlekeep, and he was thought to have perished with it.  One night he surfaced however, and started a reign of terror on the Sword Coast for several years until he was defeated by a powerful cleric of Azuth.  This ring was taken from the lich's bony finger and still worn by the cleric on the day of his death many years later.  The ring was then interred in the catacombs below Candlekeep along with him.

STATISTICS:

Armor Class: +3 bonus
Saving Throws: +3 bonus"


// mh#ring5 - Ring of Mind Shielding

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring5.itm" "override"
  SAY NAME2 "Ring of Mind Shielding"
  SAY IDENTIFIED_DESC "Ring of Mind Shielding

The first of these rings was created by drow sorcerers when the drow found too many warriors falling to the psionic powers of the illithid in the many battles the two raced waged for living space in the Underdark.  The secret to making these has since spread to the surface, and rings like these are in high demand from rulers and nobles who fear their actions may be manipulated by outside forces.

The ring completely wards the wearer's mind against all external influences.  He cannot be charmed, dominated, confused, feebleminded or stunned, and his alignment cannot be detected."

  PATCH_IF NOT ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_charm_arrays
    END

    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_confusion_arrays
    END

    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_feeblemind_arrays
    END

    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_stun_arrays
    END
  END


// mh#ring6 - Ring of Shooting Stars

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring6.itm" "override"
  SAY NAME2 "Ring of Shooting Stars"
  SAY IDENTIFIED_DESC "Ring of Shooting Stars: 'Ring of the High Mage'

This powerful and dangerous ring was crafted by elven high mages in the days of Myth Drannor.  Although initially meant to be used in the defense of the city, it ended up doing great damage to it after the sun elf houses resorted to assassinations and open violence to prevent any non-elf from participating in the Claiming Ceremony that would appoint Cormanthyr's new ruler.  It was this item that shattered the Rule Tower and, some say, began the decline of the great kingdom of Cormanthyr.  During the fall of Myth Drannor, the ring was secured by a group of mages calling themselves the Eternal Srinnala, but what happened to it afterwards is unclear.  What is clear though is that this ring, like many powerful artifacts of ancient elven magic, has the potential to do both great good and untold damage.

STATISTICS:

Abilities: Casts Melf's Minute Meteors 3/day, Chain Lightning 2/day and Meteor Swarm 1/day as a 20th level mage.
Requires: 12 Intelligence"


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= 38588		// "Melf's Minute Meteors"
  $tip(2)		= 25939		// "Chain Lightning"
  $tip(3)		= 26345		// "Meteor Swarm"
STR_VAR
  item			= "mh#ring6"
END


// mh#robe1 - Robe of the Elements

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#robe1.itm" "override"
  SAY NAME2 "Robe of the Elements"
  SAY IDENTIFIED_DESC "Robe of the Elements

This beautiful robe was custom-made by the elf Tania for <CHARNAME>.  It combines all of the powers of the more common minor mage robes like the Knave's Robe and the Robe of Fire Resistance into one more powerful item.  It also looks quite classy.

STATISTICS:

Armor Class: +1 bonus
Saving Throws: +1 vs. Poison, Polymorph and Breath
Fire Resistance: +20%
Cold Resistance: +20%
Electricity Resistance: +20%

Only usable by:
 Mage"


// mh#shld1 - Shield of the Phoenix

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#shld1.itm" "override"
  SAY NAME2 "Shield of the Phoenix +1"
  SAY IDENTIFIED_DESC "Medium Shield +1: 'Shield of the Phoenix'

The Holy Order of the Phoenix was a paladin order several hundred years ago.  It eventually fell apart due to differences in faith, but at the height of their power they were known throughout Faerun by their blazing golden shields.  Some of the higher ranking members had their shields enchanted, and these shields still exist today, most of them lying in treasure hordes somewhere in forgotten dungeons, waiting for a brave adventurer to recover them.

The sacred nature of the enchantment on this shield causes extreme physical pain to anyone of evil alignment who tries to use it.

STATISTICS:

Armor Class: +2
Fire Resistance: +30%
Weight: 6
Requires: 12 Strength

Not usable by:
 Bard
 Druid
 Mage
 Thief
 Evil characters"


// mh#shld2 - Ankheg Shield +1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#shld2.itm" "override"
  SAY NAME2 "Ankheg Shield +1"
  SAY IDENTIFIED_DESC "Ankheg Shield +1

This medium shield was created from the chitinous shell of an ankheg by the dwarven smith Brokk.  After seeing the beautiful ankheg plate that Taerum 'Thunderhammer' created from <CHARNAME>'s ankheg shell, the proud dwarf decided that no human would outdo him, by Moradin!  He then crafted this sturdy medium shield from another ankheg shell.

Like the ankheg plate that inspired it, this shield's greatest advantage is also its light weight, weighing about a third less than its metal equivalent.  Likewise, druids can use this shield without violating their vows, as no metal has been used in its construction.

STATISTICS:

Armor Class: +2
Acid Resistance: +30%
Weight: 4
Requires: 8 Strength

Not usable by:
 Bard
 Mage
 Thief"


// mh#shld3 - Meteoric Iron Shield +2

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#shld3.itm" "override"
  SAY NAME2 "Meteoric Iron Shield +2"
  SAY IDENTIFIED_DESC "Meteoric Iron Shield +2

This sturdy shield has been crafted from meteoric iron, beaten into shape by the capable hands of the dwarven smith Brokk.  The latent cosmic power in the meteoric iron has resulted in a shield of exceptional sturdiness.

Armor Class: +3 bonus
Weight: 5
Requires: 12 Strength

Not usable by:
 Bard
 Druid
 Mage
 Thief"


// mh#sper1 - Spear of Halama

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#sper1.itm" "override"
  SAY NAME2 "Spear of Halama +2"
  SAY IDENTIFIED_DESC "Spear +2: 'Spear of Halama'

This enchanted spear is said to have been gift to the elven heroine Halama from an ancient gold dragon she had befriended.  No other details of its history are known.

The wielder of this spear is immune to all kinds of true dragon breath like the searing flames of a red dragon or the freezing cold of a white.  It does not outright block other types of breath like the flames of a hell hound or the frost of a winter wolf, but it does still grant some resistance to those.

STATISTICS:

Saving Throws: +5 vs. breath
Special: Immune to all forms of true dragon breath
THAC0: +2 bonus
Damage: 1d6 +2
Damage Type: piercing
Weight: 3
Speed Factor: 4
Proficiency Type: Spear 
Type: 2-handed
Requires: 5 Strength

Not usable by:
 Cleric
 Mage
 Thief"
  
  PATCH_IF NOT ENGINE_IS "bg1 totsc"
  BEGIN
    PHP_EACH dragon_breath AS spell_name => spell_res
    BEGIN
      LAUNCH_PATCH_FUNCTION ADD_ITEM_EQEFFECT
        INT_VAR
	opcode		= 206	// Protection: from Spell
	target		= 1	// Self
	timing		= 2	// While equipped
	STR_VAR
	resource	= "%spell_res%"
      END
    END
  END


// mh#swrd1 - Terminus Est +2

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#swrd1.itm" "override"
  SAY NAME2 "Terminus Est +2"
  SAY IDENTIFIED_DESC "Bastard Sword +2: 'Terminus Est'

When lady Walraven was sentenced to death for high treason, she had but one last wish: That her delicate neck was spared from the executioner's crude axe.  The blacksmith of Walraven Keep then forged this masterwork blade for the occasion.  After the execution it was placed within the keep as a wall decoration, but not for very long.  Because of the lady's treason, Walraven Keep and the surrounding village were completely razed by a horde of orcs and ogres within a week, and the sword was taken as a trophy.  Orc shamans enchanted it, and it was wielded by their chieftain for several years until he was slain by a paladin of Tyr during a failed raid.  After that the sword has changed hands several times, usually in a violent manner.

STATISTICS:

THAC0: +2 bonus
Damage: 2d4 +2, 50% chance of additional 1d3 +1 poison damage
Damage type: slashing (and poison)
Weight: 7
Speed Factor: 6
Proficiency Type: Bastard Sword
Type: 1-handed
Requires: 11 Strength

Not usable by:
 Druid
 Cleric
 Mage
 Thief"


// mh#swrd2 - Heartsblood +1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#swrd2.itm" "override"
  SAY NAME2 "Heartsblood +1"
  SAY IDENTIFIED_DESC "Long Sword +1, +2 vs. Undead: 'Heartsblood'

This long sword was the family blade of the paladin Lyssinde Heartsblood, but she fell in battle, ironically against a horde of undead which she had grossly underestimated.  Lyssinde had no heir and no family, so her sword laid next to her body for more than a hundred years until another adventuring group found her.  This group, which included a kind-hearted priest of Ilmater, finally gave the young adventuress a decent burial and then used the sword to utterly wipe out the horde of undead that had cost Lyssinde her life.  They met with disaster themselves a few years later when drow ambushed them in the Underdark.  A drow trader named Nym later claimed the blade and sold it back to a surfacer.

This sword is always considered +2 for purposes of what it can hit, but against enemies that are not undead it performs only as a +1 sword.

STATISTICS:

THAC0: +1 bonus, +2 vs. Undead
Damage: 1d8 +1, +2 vs. Undead
Damage type: slashing
Weight: 4
Speed Factor: 4
Proficiency Type: Long Sword
Type:  1-handed
Requires: 6 Strength

Not usable by:
 Cleric
 Druid
 Mage"


// mh#swrd3 - Selune's Blessing +1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#swrd3.itm" "override"
  SAY NAME2 "Selune's Blessing +1"
  SAY IDENTIFIED_DESC "Scimitar +1, +3 vs. Lycanthropes & Undead: 'Selune's Blessing'

This scimitar is said to have been created by Selune herself in a manifestation of moonfire.  Valia, a priestess of the Moon Maiden, once got lost in the High Forest and would have perished, had a kind druid not found her and guided her back to civilization.  Later on, when Valia heard that the druids were under attack by dangerous creatures of the night, she prayed to her goddess for aid to those who had helped her.  One night under a full moon her prayers were answered when the alter glowed with milky-white light which condensed and solidified to form this scimitar.  Valia traveled to the druid grove and presented the weapon to them, and then volunteered to stay and help them fight off the threat.  Eventually they were successful, and since then this scimitar has been a beacon of hope for those who face the evil things that go bump in the night.

STATISTICS:

THAC0: +1, +3 vs Lycanthropes & Undead
Damage: 1d8 +1, +3 vs. Lycanthropes & Undead
Damage type: slashing
Weight: 3
Speed Factor: 4
Proficiency Type: Scimitar
Type: 1-handed
Requires: 10 Strength

Not usable by:
 Cleric
 Mage"

  // BG1 does not have scimitar animation
  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    WRITE_ASCII 0x0022 "S1" #2
  END


// mh#swrd4 - Lashing Sword of Samos the Skullreaver

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#swrd4.itm" "override"
  SAY NAME2 "Lashing Sword +1"
  SAY IDENTIFIED_DESC "Short Sword of Disruption +1: 'Lashing Sword of Samos the Skullreaver'

This peculiar short sword belonged to a dwarven undead hunter named Samos the Skullreaver.  It normally functions as a sword sword +1, but it can also extend a whip-like lash of force that trails blue sparks from its pommel.  This energy whip extends to 10 feet and passes harmlessly through most creatures, but any undead touched by it must save versus death at -4 or be instantly destroyed.  The wielder can choose between sword- and energy lash functions at will, but only one of the two can be in use at any time.

STATISTICS:

THAC0: +1 bonus
Damage: 1d6 +1 (melee) or 0 (lash)
Damage Type (melee): piercing
Damage Type (lash): none
Special: Undead struck by the lash must save vs. death at -4 or be destroyed
Speed Factor: 2
Weight: 3
Proficiency Type: Short Sword
Type: 1-handed
Requires: 5 Strength

Not usable by:
 Cleric
 Druid
 Mage"


LAUNCH_ACTION_FUNCTION tooltips INT_VAR
  $tip(1)		= 15529		// "Melee"
  $tip(2)		= RESOLVE_STR_REF("Energy Lash")
STR_VAR
  item			= "mh#swrd4"
END


