// Made in Heaven item pack for the Baldur's Gate trilogy


// Generate generic extra damage .eff files

OUTER_FOR (i = 1; i <= 4; ++i)
BEGIN
  // Extra damage of various types.

  CREATE EFF "mh#crsh%i%"
    WRITE_LONG	0x0010 12	// HP: Damage
    WRITE_LONG	0x001c i
    WRITE_LONG	0x0020 0
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance

  CREATE EFF "mh#slsh%i%"
    WRITE_LONG	0x0010 12	// HP: Damage
    WRITE_LONG	0x001c i
    WRITE_LONG	0x0020 16777216
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance


  // Increase to-hit/damage against specific creatures.
  //
  // Some of these already exist in BG1/BG2, but have various errors,
  // so creating them all fresh here.

  CREATE EFF "undhit%i%"
    WRITE_LONG	0x0010 178	// THAC0 vs. Creature Type
    WRITE_LONG	0x001c IDS_OF_SYMBOL("general" "undead")
    WRITE_LONG	0x0020 3
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance
    WRITE_LONG	0x0060 i

  CREATE EFF "unddam%i%"
    WRITE_LONG	0x0010 179	// Damage vs. Creature Type
    WRITE_LONG	0x001c IDS_OF_SYMBOL("general" "undead")
    WRITE_LONG	0x0020 3
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance
    WRITE_LONG	0x0060 i

  CREATE EFF "lycnhit%i%"
    WRITE_LONG	0x0010 178	// Damage vs. Creature Type
    WRITE_LONG	0x001c IDS_OF_SYMBOL("race" "lycanthrope")
    WRITE_LONG	0x0020 3
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance
    WRITE_LONG	0x0060 i

  CREATE EFF "lycndam%i%"
    WRITE_LONG	0x0010 179	// Damage vs. Creature Type
    WRITE_LONG	0x001c IDS_OF_SYMBOL("race" "lycanthrope")
    WRITE_LONG	0x0020 3
    WRITE_SHORT	0x0024 1	// Permanent
    WRITE_SHORT	0x002c 100	// 100% chance
    WRITE_LONG	0x0060 i
END


// Copy .bam files over

COPY_LARGE "%MOD_FOLDER%/item_pack/bgt/bams" "override"


// Update itemexcl.2da

COPY_EXISTING "itemexcl.2da" "override"
  APPEND_FILE TEXT "%MOD_FOLDER%/item_pack/bgt/item_exclude.txt"


// mh#amul1 - Amulet against Undead

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#amul1.itm" "override"
  SAY NAME2 "Amulet against Undead"
  SAY IDENTIFIED_DESC "Amulet against Undead

This item looks quite old and judging by the style has been forged somewhere in Mulhorand, but the history of its creation is unknown.  It is possible that it was not created on Faerun at all but instead was brought on this world when the ancient Imaskari artificers magically abducted thousands of humans from another world to serve as their slaves.  When their deities found a way to enter Toril, these slaves revolted and formed the nation of Mulhorand.

The amulet is shaped like an ankh, the symbol of life, and it bears silver runes and symbols related to dawn, the sun, light and life, all things that are anathema to undead.  Wearing this amulet helps the bearer strike true against zombies, ghouls and other soulless horrors from beyond the grave.

STATISTICS:

THAC0: +3 vs. Undead
Damage: +3 vs. Undead
Weight: 3"


// mh#amul2 - Gem of Insight

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#amul2.itm" "override"
  SAY NAME2 "Amulet of Insight"
  SAY IDENTIFIED_DESC "Gem of Insight

This necklace consists of a large multi-faceted diamond on a delicate silver chain.  If one peers inside the diamond, the holy symbol of Oghma, god of knowledge can be seen at the center.  Most likely this item was created by the clergy of Oghma, but for what exact purpose is unknown.  Most likely, it was just to advance knowledge and ideas in general.

While worn, this magical gem enhances both the intelligence and wisdom of the wearer.  If the wearer so chooses the gem can enhance their intelligence permanently, but by doing so the gem and the wisdom it brings will be permanently lost.

STATISTICS:

Intelligence: +1 bonus
Wisdom: +1 bonus
Special: Can enhance intelligence permanently, but by doing so the gem is forever lost.
Weight: 1"


// mh#amul3 - Necklace of Prayer Beads

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#amul3.itm" "override"
  SAY NAME2 "Necklace of Prayer Beads"
  SAY IDENTIFIED_DESC "Necklace of Prayer Beads

Necklaces like these are sometimes created by the clergy of Tymora for sale to adventurers in need of a little extra preparation.  The clergy claims they are doing it to help adventurers be successful in their cause, but the more cynical remark that an adventurer already has to be pretty successful in order to even be able to afford one of these items.

STATISTICS:

Abilities: Bless 3/day, Cure Serious Wounds 1/day and Neutralize Poison 1/day, all as a 12th level cleric

Only usable by:
  Cleric
  Druid"

  // BG1 engine does not support charges per day
  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION ALTER_ITEM_HEADER
      INT_VAR
      charges		= 10
      flag_recharge	= 0
    END
  END


// mh#armr1 - Green Dragon Scale

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#armr1.itm" "override"
  SAY NAME2 "Green Dragon Scale"
  SAY IDENTIFIED_DESC "Green Dragon Scale

This armor was expertly crafted by the dwarven smith Brokk from green dragon scales which <CHARNAME> found in the depths of Durlag's Tower.  Whom exactly slew the green dragon that these scales were harvested from is not known, but most likely it was the dwarven hero Durlag himself.

STATISTICS:

Armor Class: 0
Special: wearer is immune to poison
Weight: 8
Requires: 6 Strength

Not usable by:
 Bard
 Mage
 Thief"

  // Apply CamDawg's full poison immunity macro on BG2 or better engine
  PATCH_IF ENGINE_IS "bg2 tob bgee bg2ee"
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_poison_arrays
    END
  END


// mh#armr2 - Eversing +2

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#armr2.itm" "override"
  SAY NAME2 "Eversing +2"
  SAY IDENTIFIED_DESC "Plate Armor +2: 'Eversing'

This magnificent set of silvered plate was created hundreds of years ago by a joined effort between master dwarven smiths from Dorn's Deep and elven high mages from the Hand of the Seldarine.  Unfortunately it was stolen from the dwarven vaults and later found on the body of an orc chieftain by the elves, sowing deep distrust between the two races.  This eventually led to the fall of both the Hand of the Seldarine and Dorn's Deep to orc hordes.

The silver coating on this armor never loses its shine and may occasionally deflect hostile spells away from the wearer.

STATISTICS:

Armor Class: 1
Saving Throws: +2 vs. Spells
Magic Resistance: +5%
Weight: 25
Requires: 12 Strength
Not Usable By:
 Bard
 Druid
 Mage
 Thief"


// mh#armr3 - Winter Wolf Hide +1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#armr3.itm" "override"
  SAY NAME2 "Winter Wolf Hide +1"
  SAY IDENTIFIED_DESC "Winter Wolf Hide +1

Expertly sown together for <CHARNAME> by the elven seamstress Tania, this hide armor is actually surprisingly comfortable.  The luxurious white winter wolf pelts keep the wearer pleasantly warm in the highlands of the Cloudpeaks, or any other cold place for that matter.  Tania seems to have woven a little elven magic into it as well, as some of the winter wolf's immunity to cold has been preserved and the armor restricts thieves only half as much as hide armor should.

However, since hide armor has a reputation as 'barbaric', and still remains somewhat uncomfortable and smelly, shops generally buy and sell it for a fairly low price.

STATISTICS:

Armor Class: 5
Cold Resistance: +30%
Penalties:
  Stealth: -10%
  Lockpicking: -5%
  Find/Remove Traps: -5%
  Pick Pockets: -15%
Weight: 30

Not usable by:
 Mage"


// mh#belt1 - Girdle of Dwarvenkind: 'Moradin's Blessing'

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#belt1.itm" "override"
  SAY NAME2 "Girdle of Dwarvenkind"
  SAY IDENTIFIED_DESC "Girdle of Dwarvenkind: 'Moradin's Blessing'

Priests of Moradin sometimes grant belts like this one to non-dwarves who have done a great service to dwarvenkind.  Most dwarves will treat anyone wearing one of these as a trusted friend and clansmember.

The sturdy belt contains a powerful blessing that grants the wearer many of the racial bonuses that dwarves enjoy, like infravision and enhanced constitution.  Unfortunately for the wearer, some of the dwarven gruffness also rubs off on them, hurting their charisma slightly.

STATISTICS:

Constitution: +1 bonus
Charisma: -1 penalty
Saving Throws: +3 vs. Poison, Wands and Spells
Special: wearer gains infravision like a dwarf
Weight: 2

Not usable by:
 Dwarf
 Gnome"


// mh#blun1 - Slime Crusher +1

CREATE EFF "mh#blun1"
  WRITE_LONG	0x0010 178	// THAC0 vs. Creature Type
  WRITE_LONG	0x001c IDS_OF_SYMBOL("race" "slime")
  WRITE_LONG	0x0020 4
  WRITE_SHORT	0x0024 1	// Permanent
  WRITE_SHORT	0x002c 100	// 100% chance
  WRITE_LONG	0x0060 3

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#blun1.itm" "override"
  SAY NAME2 "Slime Crusher +1"
  SAY IDENTIFIED_DESC "Morning Star +1, +4 vs. Slimes: 'Slime Crusher'

This enchanted morning star was crafted by a troll shaman of the Silver Marshes in an effort to deal with an infestation of mustard jellies.  It was effective eventually, but the tribe suffered heavy losses in the process and was later easily wiped out by a band of human- and dwarven adventurers.

This morning star is considered a +4 weapon for purposes of what it can hit, but against enemies that aren't slimes it performs as a +1 weapon only.

STATISTICS:

THAC0: +1, +4 vs. Slimes
Damage: 2d4 +1, +4 vs. Slimes
Damage type: crushing
Weight: 10
Speed Factor: 6
Proficiency Type: Flail/Morning Star
Type: 1-handed
Requires: 11 Strength
Not Usable By:
 Druid
 Mage
 Thief"


// mh#boot1 - Feather Tabi

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#boot1.itm" "override"
  SAY NAME2 "Feather Tabi"
  SAY IDENTIFIED_DESC "Feather Tabi: 'Boots of the Master Ninja'

These enchanted split-toe boots hail from faraway Kara-Tur and are a rare sight on the Sword Coast.  The exact process of enchanting them is only known to some clans of ninja and they are quite secretive about it.  How this pair made it all the way to the Sword Coast is unclear.  Most likely, their former owner met with disaster while on a mission and was forced to leave them behind.  Whether he or she is still alive and still looking for them remains to be seen.

While worn these boots greatly reduces the force the wearer's weight excerts on the surface they are walking over.  This makes it a lot easier to walk silently, and also reduces the likelyhood of setting off certain traps.

STATISTICS:

Stealth: +25%
Find/Remove Traps: +10%
Weight: 2

Only usable by:
 Thief"


// mh#clck1 - Mutamin's Cloak

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#clck1.itm" "override"
  SAY NAME2 "Mutamin's Cloak"
  SAY IDENTIFIED_DESC "Mutamin's Cloak

This cloak was worn by the mad wizard Mutamin before <CHARNAME> slew him in the field east of Beregost.  There is no known prior history, most likely the mad gnome created it himself so he would be safe around his 'pets'.

STATISTICS:

Special: wearer is immune to all forms of petrification
Weight: 3"

  // Apply CamDawg's full petrification immunity macro on BG2 or better engine
  PATCH_IF ENGINE_IS "bg2 tob bgee bg2ee"
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_petrification_arrays
    END
  END


// mh#clck2 - Battlecloak of Vycaena

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#clck2.itm" "override"
  SAY NAME2 "Battlecloak of Vycaena"
  SAY IDENTIFIED_DESC "Battlecloak of Vycaena

This voluminous, emerald-green cloak is trimmed with intricate designs done in gold thread.  Each of its two clasps is a golden disk engraved with the crest of a long-extinct Calishite noble family and set with a small emerald.  This alone would already make the cloak worth a small fortune, but it also bears a powerful enchantment to protect its wearer in battle.

The exact method of making these cloaks is known to only a few reclusive wizards in the Shining South, and the precious gems and rare materials involved in the process make creating a new one a hard and dangerous task.  As a result, only about a dozen of these cloaks are known to exist, and for one to make its way to the Sword Coast is a rare occurrence indeed.

STATISTICS:

Armor Class: +4 bonus
Saving Throws: +1 bonus
Weight: 3"


// mh#clck1 - Cloak of Arachnida

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#clck3.itm" "override"
  SAY NAME2 "Cloak of Arachnida"
  SAY IDENTIFIED_DESC "Cloak of Arachnida: 'Lloth's Caress'

This dark cloak was created by drow sorcerers, but how it came to leave their dark realm is not exactly known.  Most likely an overconfident drow was slain during a nightly surface raid and the cloak taken from his corpse.  Precious little is known about what happened to it on the surface either, something in the dark elven magic used to create this item seems to resist exact divination.  A few adventurers are known to have used it on various quests, but details are sketchy at best.

The wearer of this cloak can easily move through all spider webs without getting stuck, including those created by the wizard spell Web.  It also helps in resisting the poisons of arachnids.

STATISTICS:

Saving Throws: +2 vs. Poison
Special: Wearer is immune to the Web spell and all spider webbing.
Abilities: Casts Web as a 12th level wizard twice per day.
Weight: 3"

  // BG1 engine does not support charges per day
  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    LAUNCH_PATCH_FUNCTION ALTER_ITEM_HEADER
      INT_VAR
      charges		= 20
      flag_recharge	= 0
    END
  END

  // Apply CamDawg's full web immunity macro on BG2 or better engine
  PATCH_IF ENGINE_IS "bg2 tob bgee bg2ee"
  BEGIN
    LAUNCH_PATCH_FUNCTION cd_apply_batch
      STR_VAR
      array_name	= cd_immunity_web_arrays
    END
  END


// mh#hamm1 - Thronumin +3

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#hamm1.itm" "override"
  SAY NAME1 "Thronumin +3"
  SAY IDENTIFIED_DESC "War Hammer +3, Defender: 'Thronumin'

Thronumin, 'The Hammer of the Meteor', was forged almost a thousand years ago.  A meteor from Realmspace struck Aber-Toril, falling into a remote area of the Cloudpeak mountains and burying itself deep underground.  Dwarves from a now forgotten clan eventually tunneled to it and found that the meteor's core was almost pure iron.  From it a number of powerful weapons and armor were forged, but most have have been lost over the years.

Several dwarven runes have been inscribed into the head, glowing with power.  The enchantment on this weapon is quite formidable, not only enabling it to strike hard and true but also granting additional protection to the wielder.

STATISTICS:

THAC0: +3 bonus
Damage: 1D4 +4
Damage type: crushing
Armor Class: +1 bonus
Weight: 4
Speed Factor: 1
Proficiency Type: War Hammer
Type: 1-handed
Requires: 9 Strength

Not usable by:
 Druid
 Mage
 Thief"


// mh#helm1 - Helm of Valor

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#helm1.itm" "override"
  SAY NAME2 "Helm of Valor"
  SAY IDENTIFIED_DESC "Helm of Valor

These ornate golden helms are sometimes worn into battle by elven generals and commanders of Evermeet, Evereska or other elven nations.  This particular one was found in the ruins of Myth Drannor and probably belonged to an elven commander defending the city against the Army of Darkness.

Wearing this helm allows one to mentally will arrows and other projectiles away, making it less likely that one strikes true and reducing the damage even when this happens.  This allows the elven commander to remain upright even when under fire, and serve as an inspiration to his men.  However, because the helm operates on the willpower of the wearer, it can only be used effectively by people with high wisdom.

STATISTICS:

Armor Class: +3 vs. Missiles
Special: protects against critical hits, reduces missile damage by 50%
Requires: 13 Wisdom
Weight: 2

Not usable by:
 Bard
 Mage
 Thief"


// mh#ioun1 - Lush Emerald Ioun Stone

COPY_EXISTING "%MOD_FOLDER%/item_pack/bgt/items/mh#ioun1.itm" "override"
  SAY NAME1 "Ioun Stone"
  SAY NAME2 "Lush Emerald Ioun Stone"
  SAY UNIDENTIFIED_DESC "This is a small stone that floats in an orbit around the owner's head.  Simply equip the stone to set it in its orbit.  These obviously magical stones have different properties depending on their color."
  SAY IDENTIFIED_DESC "Lush Emerald Ioun Stone

Deep green ioun stones like this one are sometimes found between the roots of ancient oaks and other old trees.  Followers of Sylvanus consider them sacred to the Oak Father, and elves likewise consider them gifts from Rillifane Ralathil, the Leaflord.  Whether either of these gods actually has anything to do with the creation of these stones is unknown.  Some theorize they are buried treasures of old, probably from some tree-worshiping cult, while others speculate they are formed by some yet unknown natural or magical process.

In the hands of a druid or someone with a similarly strong connection to nature, this ioun stone becomes a powerful magical item.  But to anyone else it remains an inert, if very beautiful stone.

STATISTICS:

Armor Class: +1 bonus
Regeneration: 1 hp/5 rounds
Weight: 2

Only usable by:
 Druid"


// mh#misc1 - Green Dragon Scales

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#misc1.itm" "override"
  SAY NAME2 "Green Dragon Scales"
  SAY IDENTIFIED_DESC "Green Dragon Scales

These shiny emerald scales were harvested from the corpse of a green dragon and seem to have been preserved in some way.  A capable smith should be able to craft these into a suit of armor."


// mh#potn1 - Oil of Acid Resistance

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#potn1.itm" "override"
  SAY NAME2 "Oil of Acid Resistance"
  SAY IDENTIFIED_DESC "Oil of Acid Resistance

This is a black, viscous and non-flamable oil.  When applied to exposed equipment and skin, it confers virtual immunity to all acids and other corrosive agents.  All acid damage is reduced by 90%, on top of any other resistances the person might have.  The effect lasts for 10 turns, or until dispelled."


// mh#ring1 - Ring of Warmth

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring1.itm" "override"
  SAY NAME2 "Ring of Warmth"
  SAY IDENTIFIED_DESC "Ring of Warmth

A favorite among mountaineers, explorers and others whose activities get then into cold areas (including, of course, adventurers), the enchantment on this ring allows the wearer to remain comfortable in sub-zero temperatures.  Damage from extreme cold like white dragon breath or a wizard's Cone of Cold spell is also reduced.

STATISTICS:

Cold Resistance: +20%"


// mh#ring2 - Ring of the Neophyte

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring2.itm" "override"
  SAY NAME2 "Ring of the Neophyte"
  SAY IDENTIFIED_DESC "Ring of the Neophyte

A lesser version of the fabled Ring of Wizardry, rings like these are sometimes granted to a favorite apprentice when they complete their studies and are ready to set out on their own.  Other, more demanding masters might require their apprentices to complete forging one of their own as a sort of final exam.

This particular one bears a mage sigil that you don't recognize and does not respond to divination magic.  Its creator may be long forgotten - or value their privacy.

STATISTICS:

Spells: one extra 1st level spell slot

Only usable by:
 Mage"


// mh#ring3 - Ring of Toughness

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring3.itm" "override"
  SAY NAME2 "Ring of Toughness"
  SAY IDENTIFIED_DESC "Ring of Toughness

This ring is a fairly plain steel band with only minimal enamel decoration.  It bears a minor enchantment that gives the wearer a small boost in vitality.

It's not known who created the first of these rings, but they occasionally show up in places where there has been a large conflict, probably created by combat priests or war wizards.

STATISTICS:

Hit Points: +3 maximum"


// mh#ring4 - Ring of Protection +3

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#ring4.itm" "override"
  SAY NAME2 "Ring of Protection +3"
  SAY IDENTIFIED_DESC "Ring of Protection +3: 'Ring of the Lich'

This ring is a creation of the Netherese lich Trachir the Elder, also known as the Ebon Skull.  When Karsus cast his fateful spell that destroyed High Netheril, Trachir had just completed the final rituals and drank the lethal potion that would transform his body into an undead horror.  Trachir's enclave plunged into the Trackless Sea several miles from the coast of Candlekeep, and he was thought to have perished with it.  One night he surfaced however, and started a reign of terror on the Sword Coast for several years until he was defeated by a powerful cleric of Azuth.  This ring was taken from the lich's bony finger and still worn by the cleric on the day of his death many years later.  The ring was then interred in the catacombs below Candlekeep along with him.

STATISTICS:

Armor Class: +3 bonus
Saving Throws: +3 bonus"


// mh#robe1 - Robe of the Elements

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#robe1.itm" "override"
  SAY NAME2 "Robe of the Elements"
  SAY IDENTIFIED_DESC "Robe of the Elements

This beautiful robe was custom-made by the elf Tania for <CHARNAME>.  It combines all of the powers of the more common minor mage robes like the Knave's Robe and the Robe of Fire Resistance into one more powerful item.  It also looks quite classy.

STATISTICS:

Armor Class: +1 bonus
Saving Throws: +1 vs. Poison, Polymorph and Breath
Fire Resistance: +20%
Cold Resistance: +20%
Electricity Resistance: +20%

Only usable by:
 Mage"


// mh#shld1 - Shield of the Phoenix

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#shld1.itm" "override"
  SAY NAME2 "Shield of the Phoenix +1"
  SAY IDENTIFIED_DESC "Medium Shield +1: 'Shield of the Phoenix'

The Holy Order of the Phoenix was a paladin order several hundred years ago.  It eventually fell apart due to differences in faith, but at the height of their power they were known throughout Faerun by their blazing golden shields.  Some of the higher ranking members had their shields enchanted, and these shields still exist today, most of them lying in treasure hordes somewhere in forgotten dungeons, waiting for a brave adventurer to recover them.

The sacred nature of the enchantment on this shield causes extreme physical pain to anyone of evil alignment who tries to use it.

STATISTICS:

Armor Class: +2
Fire Resistance: +30%
Weight: 6
Requires: 12 Strength

Not usable by:
 Bard
 Druid
 Mage
 Thief
 Evil characters"


// mh#shld2 - Ankheg Shield +1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#shld2.itm" "override"
  SAY NAME2 "Ankheg Shield +1"
  SAY IDENTIFIED_DESC "Ankheg Shield +1

This medium shield was created from the chitinous shell of an ankheg by the dwarven smith Brokk.  After seeing the beautiful ankheg plate that Taerum 'Thunderhammer' created from <CHARNAME>'s ankheg shell, the proud dwarf decided that no human would outdo him, by Moradin!  He then crafted this sturdy medium shield from another ankheg shell.

Like the ankheg plate that inspired it, this shield's greatest advantage is also its light weight, weighing about a third less than its metal equivalent.  Likewise, druids can use this shield without violating their vows, as no metal has been used in its construction.

STATISTICS:

Armor Class: +2
Acid Resistance: +30%
Weight: 4
Requires: 8 Strength

Not usable by:
 Bard
 Mage
 Thief"


// mh#swrd1 - Terminus Est +2

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#swrd1.itm" "override"
  SAY NAME2 "Terminus Est +2"
  SAY IDENTIFIED_DESC "Bastard Sword +2: 'Terminus Est'

When lady Walraven was sentenced to death for high treason, she had but one last wish: That her delicate neck was spared from the executioner's crude axe.  The blacksmith of Walraven Keep then forged this masterwork blade for the occasion.  After the execution it was placed within the keep as a wall decoration, but not for very long.  Because of the lady's treason, Walraven Keep and the surrounding village were completely razed by a horde of orcs and ogres within a week, and the sword was taken as a trophy.  Orc shamans enchanted it, and it was wielded by their chieftain for several years until he was slain by a paladin of Tyr during a failed raid.  After that the sword has changed hands several times, usually in a violent manner.

STATISTICS:

THAC0: +2 bonus
Damage: 2d4 +2, 50% chance of additional 1d3 + 1 poison damage
Damage type: slashing (and poison)
Weight: 7
Speed Factor: 6
Proficiency Type: Bastard Sword
Type: 1-handed
Requires: 11 Strength

Not usable by:
 Druid
 Cleric
 Mage
 Thief"


// mh#swrd2 - Heartsblood +1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#swrd2.itm" "override"
  SAY NAME2 "Heartsblood +1"
  SAY IDENTIFIED_DESC "Long Sword +1, +2 vs. Undead: 'Heartsblood'

This long sword was the family blade of the paladin Lyssinde Heartsblood, but she fell in battle, ironically against a horde of undead which she had grossly underestimated.  Lyssinde had no heir and no family, so her sword laid next to her body for more than a hundred years until another adventuring group found her.  This group, which included a kind-hearted priest of Ilmater, finally gave the young adventuress a decent burial and then used the sword to utterly wipe out the horde of undead that had cost Lyssinde her life.  They met with disaster themselves a few years later when drow ambushed them in the Underdark.  A drow trader named Nym later claimed the blade and sold it back to a surfacer.

This sword is always considered +2 for purposes of what it can hit, but against enemies that are not undead it performs only as a +1 sword.

STATISTICS:

THAC0: +1 bonus, +2 vs. Undead
Damage: 1d8 +1, +2 vs. Undead
Damage type: slashing
Weight: 4
Speed Factor: 4
Proficiency Type: Long Sword
Type:  1-handed
Requires: 6 Strength

Not usable by:
 Cleric
 Druid
 Mage"


// mh#swrd3 - Selune's Blessing +1

COPY "%MOD_FOLDER%/item_pack/bgt/items/mh#swrd3.itm" "override"
  SAY NAME2 "Selune's Blessing +1"
  SAY IDENTIFIED_DESC "Scimitar +1, +3 vs. Lycanthropes & Undead: 'Selune's Blessing'

Hundreds of years ago, a cleric of Selune got lost in the High Forest, and would surely have perished if she hadn't been found by a kind-hearted druid.  He introduced her to his circle and they became friends and, despite their differences in faith, lovers.  At some point when horrid monsters threated the forest, the cleric prayed to her goddess under the light of a full moon to help her friends.  Suddenly milky white light flooded the altar and condensed into solid form, creating this blessed scimitar.  The Selunite gave it to her druidic friend and together they successfully defended the forest, after which they married and lived a long and happy life.  This scimitar has remained a beacon of hope and the bane of things that go bump in the night ever since.

STATISTICS:

THAC0: +1, +3 vs Lycanthropes & Undead
Damage: 1d8 +1, +3 vs. Lycanthropes & Undead
Damage type: slashing
Weight: 3
Speed Factor: 4
Proficiency Type: Scimitar
Type: 1-handed
Requires: 10 Strength

Not usable by:
 Cleric
 Mage"

  // BG1 does not have scimitar animation
  PATCH_IF ENGINE_IS "bg1 totsc"
  BEGIN
    WRITE_ASCII 0x0022 "S1" #2
  END


