// BG1 compatibility hacks

ACTION_IF NOT FILE_EXISTS "override/bg1_compat_hacks.mih"
BEGIN
  COPY "%MOD_FOLDER%/dummy.mih" "override/bg1_compat_hacks.mih"


  // Create missing attack items

  COPY_EXISTING "p1-4.itm" "override/p2-8.itm"
    LAUNCH_PATCH_FUNCTION ALTER_ITEM_HEADER
      INT_VAR
      dicenumber	= 2
    END


  // Restore missing Buckler +1 (shld17)

  COPY_LARGE "%MOD_FOLDER%/lib/bg1_compat/ishld17.bam" "override"

  COPY "%MOD_FOLDER%/lib/bg1_compat/shld17.itm" "override"
    SAY NAME2 "Buckler +1"
    SAY IDENTIFIED_DESC "A buckler is a small shield of wood or metal that fastens to the forearm.  Because of its size it is light and can be worn with very little restriction to movement.  This buckler has some form of generic enchantment, making it more resistant to blows.

STATISTICS:

Armor Class Bonus:  2
Special:  No Missile/Piercing Attack Protection
Weight:  2
Requires: 4 Strength
Unusable By:
 Mage"


  // Copy in extended state.bams (from ToB, uncompressed)

  COPY "%MOD_FOLDER%/lib/bg1_compat/states.bam" "override"


  // Compile initin15 script

  LAUNCH_ACTION_FUNCTION compile_dialog_or_script
    STR_VAR
    path_to_file	= "%MOD_FOLDER%/lib/bg1_compat/initin15.baf"
  END
END


